name: sync-files-on-readme

on:
  push:
    branches:
      - master
jobs:
  build:
    # needs: nothing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Git stuff
        run: |
          touch somefile.txt
          echo "hello" > somefile.txt
          git checkout -b gh-pages
          git add somefile.txt
          git commit -m "message"
          git remote set-url origin https://github.com/tinamthomas/docker-node-server.git
          git push origin HEAD:gh-pages